### ISSUE TITLE
AWS request signing support 

### ISSUE THREAD

**Issue by rimutaka** [elastic/elasticsearch-rs#137]
AWS runs its own distribution of ES called ElasticSearch Service, which is mostly compatible with this library, except for the missing request signing feature. It makes impossible to use this library with IAM-based access control. 

I totally understand **your unwillingness to support their distro** as stated in https://discuss.elastic.co/t/any-way-to-sign-requests-to-aws-elasticsearch-using-asp-net-nest/245938, but **I think this strategy is counter-productive**. Consider my case ...

I am building an app prototype on AWS. ES is part of my stack. I need to get everything up and running fast and then switch to a properly supported AWS set up by Elastic. I started with AWS ES Service ad would like to use this client lib to make it easier to switch to Elastic later, but I can't. So I am ending up with a lot of custom-built code to talk to the ES instance which only entrenches me deeper in AWS services.

### Possible solutions:
1. Add AWS request signing
2. Allow intercepting the request to add our own headers after it was constructed (could be an even more flexible solution)

I'm happy to put in some effort into a PR if you are interested.

### Background info:

- [AWS ES access control](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html)
- [Signing process](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)
- [Rust signature implementation](https://docs.rs/rusoto_signature/0.45.0/rusoto_signature/index.html)

**Comment by treykasada** [comment]
Just hit this as well. Would love to see some support here.

A possible approach could be to redefine `Transport` as a trait, allowing developers to specify their own implementation for the `send` method. It should then be possible to create a simple wrapper over one of the builtin transports that could leverage something like `rusoto_signature` to do the signing.

**Comment by russcam** [comment]
Thanks for opening @rimutaka. 

Whilst the client won't ship with AWS request signing as part of the package, its architecture should make it possible for a user to extend the client to support this.

> I am building an app prototype on AWS. ES is part of my stack. I need to get everything up and running fast and then switch to a properly supported AWS set up by Elastic. I started with AWS ES Service ad would like to use this client lib to make it easier to switch to Elastic later, but I can't. So I am ending up with a lot of custom-built code to talk to the ES instance which only entrenches me deeper in AWS services.

Genuine question- Have you considered [using Elastic Cloud instead of AWS Elasticsearch](https://www.elastic.co/aws-elasticsearch-service)? It's _super easy_ to spin up a cluster [on Elasticsearch service on Elastic Cloud, running on AWS](https://www.elastic.co/elasticsearch/service), be [billed for it through AWS Marketplace](https://www.elastic.co/blog/get-hosted-elasticsearch-on-your-aws-bill-with-elastic-cloud), and [configure private link to allow communication over internal networks](https://www.elastic.co/blog/improve-network-security-elastic-cloud-traffic-filters). You'd also be able to use a bunch of different credentials such as tokens, API keys (and SAML or OpenId Connect SSO on higher tiers).

> A possible approach could be to redefine Transport as a trait

My intention originally was to make `Transport` a trait 🙂 One problem with this right now is that traits cannot have `async` functions, so defining `send()` on a `pub trait Transport` is not possible without using the [`async-trait` crate](https://github.com/dtolnay/async-trait). I would like to better understand the ramifications in using `async-trait`, including performance, before committing to any change though.

Another approach could be to expose a way to set a function that can be called just before the request is made, which I think is what @rimutaka is proposing.

**Comment by rimutaka** [comment]
I agree that `async-trait` is probably an overkill just for this narrow use case. An optional signing function is an easier solution. The signing code doesn't need to be part of this crate. It can come from `rusoto-signature` and be added as an example.

**Comment by treykasada** [comment]
@russcam If it helps, `rusoto` makes fairly liberal use of that crate, so it some semblance of precedent there.

To me, this kind of functionality seems almost exactly like what `Transport` is conceptually for (in terms of where it sits in the architecture), but honestly, either approach would work. 🙂

**Comment by meghashyam6** [comment]
@rimutaka have you been able to use this crate to connect to AWS ES eventually?

**Comment by swallez** [comment]
AWS is now running OpenSearch, a fork of Elasticsearch that has since then diverged substantially. This library is meant to be used with Elasticsearch, and does not provide support for OpenSearch.
