### ISSUE TITLE
[ENHANCEMENT] index and create method argument from BulkOperation

### ISSUE THREAD

**Issue by Stargateur** [elastic/elasticsearch-rs#154]
[`index`](https://docs.rs/elasticsearch/7.10.0-alpha.1/elasticsearch/struct.BulkOperation.html#method.index) is not logic, if I understand correctly, the purpose of index is "create or replace", so why it doesn't take a id argument like create, that is almost equivalent.

Possible fix:

- index and create take an `Into<Option<String>>`
- create should not take an id argument

**Comment by russcam** [comment]
Hi @Stargateur, the bulk operations model the [bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html):

- An index operation optionally takes an _id; if the _id is specified then check if a document exists with that _id and if it does, overwrite it and increment the version number, otherwise create it. index operations are frequently used to index documents without _id, so `BulkOperation::index(...)` does not enforce a value to be passed, but if an _id needs to be specified, [`id(...)` can be called on the returned `BulkIndexOperation`](https://docs.rs/elasticsearch/7.10.0-alpha.1/elasticsearch/struct.BulkIndexOperation.html#method.id)
- A create operation requires an _id**¹**, so  `BulkOperation::create(...)` requires it to be passed.

**¹** this has recently changed with the introduction of [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html). A version of the client can be used with any version of Elasticsearch with the same major version though, so we probably still want to enforce an _id to be passed, because there are Elasticsearch 7.x versions where the _id is required for a create operation.

**Comment by Stargateur** [comment]
the doc clearly state in create:

>  _id (Optional, string) The document ID. If no ID is specified, a document ID is automatically generated.

it's only required by delete so I maintain what I said
